# Generated by Django 4.0.4 on 2022-07-26 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Web Development', 'Web Development'), ('Information System Development', 'Information System Development'), ('Mobile App Development', 'Mobile App Development'), ('Graphics Design', 'Graphics Design')], max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('scheduled', models.BooleanField(default=False)),
                ('descriptive_purpose', models.TextField(null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, choices=[('Ecommerce', 'Ecommerce'), ('Informative', 'Informative'), ('Blog', 'Blog'), ('Advertisement', 'Advertisement'), ('Portfolio', 'Portfolio'), ('Other', 'Other')], max_length=255, null=True)),
                ('other', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('theme', models.CharField(blank=True, max_length=255, null=True)),
                ('sys_type', models.CharField(choices=[('Management', 'Management'), ('Financial', 'Financial'), ('Inventory', 'Inventory')], max_length=225, null=True)),
                ('modules', models.TextField(null=True)),
                ('banner_type', models.CharField(choices=[('Teardrop', 'Teardrop'), ('Backdrop', 'Backdrop'), ('Rollup', 'Rollup')], max_length=255, null=True)),
                ('graphic_type', models.CharField(choices=[('Cards', 'Cards'), ('Banners', 'Banners')], max_length=255, null=True)),
                ('apper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apper', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleName', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.job')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Web Development', 'Web Development'), ('Information System Development', 'Information System Development'), ('Mobile App Development', 'Mobile App Development'), ('Graphics Design', 'Graphics Design')], max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('viewed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('viewed', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
